### ISSUE TITLE
Receiving `ERROR - Body content could not be parsed to dict.` on everything

### ISSUE THREAD

**Issue by im-batman** [alverelt/gpscraper#2]
I installed with pip, ran the exact demo line provided in the README, and received this error.
```
>>> searches = [s for s in gp.search('github')]
2021-07-30 20:09:40,843 - ERROR - Body content could not be parsed to dict.
```

**Comment by alverelt** [comment]
Thanks for the message, i've tested all the functions and *App reviews* is
the only one currently working.

I will work on that this weekend.

**Comment by alverelt** [comment]
> I installed with pip, ran the exact demo line provided in the README, and received this error.
> 
> ```
> >>> searches = [s for s in gp.search('github')]
> 2021-07-30 20:09:40,843 - ERROR - Body content could not be parsed to dict.
> ```

Hi im-batman, i got other things to do this week, but it is already fixed, please download new version. =)

**Comment by im-batman** [comment]
> > I installed with pip, ran the exact demo line provided in the README, and received this error.
> > ```
> > >>> searches = [s for s in gp.search('github')]
> > 2021-07-30 20:09:40,843 - ERROR - Body content could not be parsed to dict.
> > ```
> 
> Hi im-batman, i got other things to do this week, but it is already fixed, please download new version. =)

It's alive! Very nicely done. :)
